Psl 218 convert pastel gtest
pastelnetwork/pastel pull request #107
Opened 2022-01-21 17:18 UTC by tanlemin91

2022-01-26 07:00 UTC, akobrin1 requested changes
some files needs to be merged with the latest master branch (like interpreter.h|cpp).
Please rebase on current master branch.

2022-01-26 15:18 UTC, tanlemin91 commented on src/gtest/test_sighash.cpp
> +extern UniValue read_json(const string& jsondata);
done thanks

2022-01-26 15:18 UTC, tanlemin91 commented on src/script/interpreter.cpp
> -#include <enum_util.h>
done thanks

2022-01-26 15:18 UTC, tanlemin91 commented on src/script/interpreter.cpp
> +typedef v_uint8 valtype;
done thanks

2022-01-26 15:19 UTC, tanlemin91 commented on src/script/interpreter.h
> +#ifndef BITCOIN_SCRIPT_INTERPRETER_H
done thanks

2022-01-27 13:48 UTC, akobrin2 approved these changes

2022-01-27 13:49 UTC, akobrin1 approved these changes

2022-01-27 13:51 UTC, merged