Updated CMasternodeGovernance::VoteForTicket and CMasternodeGovernance::AddTicket pre-conditions
pastelnetwork/pastel pull request #123
Opened 2022-04-13 18:53 UTC by TimothyBanks

### A. Improving governance voting logic

**Currently any active masternode can register governance payment ticket (CMasternodeGovernance::AddTicket), we need to add two more checks:**

check that MN is indeed enabled, by calling - CMasternode::IsEnabled() and check that it is “old enough”, this can be checked by comparing masternode’s broadcast message time with the current timethere is already method for that CMasternode::IsBroadcastedWithinold enough is 30 days (17280 blocks)

Same as above for Voting for ticket - CMasternodeGovernance::VoteForTicket

**B. Improving winner decision**

Governance ticket winners is decided if ticket gets 51% of Yes votes and 10% of masternode voted for it (CGovernanceTicket::IsWinner)

Currently 10% is calculated from the number of ALL masternodes in the network, this has to be changed to use only number of Enabled MNs

use CMasternodeMan::CountEnabled

2022-04-18 13:09 UTC, TimothyBanks commented on src/mnode/mnode-governance.cpp
> +    if (masterNode.IsBroadcastedWithin(thirty_days)){
I'm still a bit unsure how to set up the test to get this condition to pass.

2022-04-18 13:09 UTC, TimothyBanks commented on src/mnode/mnode-governance.cpp
> +    if (masterNode.IsBroadcastedWithin(thirty_days)){
I'm still a bit unsure how to set up the test to get this condition to pass.

2022-05-04 19:48 UTC, akobrin1 requested changes
Will definitely need to rebase on master - I made some changes in mn-governance.cpp|h files.

2022-05-04 19:48 UTC, akobrin1 commented on src/mnode/mnode-governance.cpp
> +bool CMasternodeGovernance::CanVote(std::string& strErrorRet) const
can make it noexcept...
IsActiveMasterNode,IsEnabled,IsBroadcastedWithin - noexcept
Just make also CMasternodeMan::Get const noexcept- it does not throw any exceptions

2022-05-04 19:48 UTC, akobrin1 commented on src/mnode/mnode-governance.cpp
> +    constexpr static auto thirty_days_in_seconds = int32_t{30 * 24 * 60 * 60};
you could just declare constexpr static int32_t (or int as the type of parameter in IsBroadcastedWithin function)

2022-05-04 19:48 UTC, akobrin1 commented on src/mnode/mnode-governance.h
> +    bool CanVote(std::string& strErrorRet) const;
noexcept

2022-05-04 19:48 UTC, akobrin1 commented on src/mnode/mnode-governance.h
> +    bool CanVote(std::string& strErrorRet) const;
Please make it protected & virtual - this way it is easier to write tests. Will just mock it later on.

2022-05-10 14:01 UTC, a-ok123 approved these changes

2023-10-04 00:48 UTC, closed without merging