Add getblockdeltas function on Pastel.
pastelnetwork/pastel pull request #18
Opened 2021-05-31 16:49 UTC by tsimafeisetchinava000

- Add getblockdeltas function on Pastel source code.
   https://github.com/zcash/zcash/search?q=getblockdeltas

2021-06-01 02:00 UTC, akobrin1 requested changes

2021-06-01 02:00 UTC, akobrin1 commented on src/txmempool.cpp
> +    std::map<CSpentIndexKey, CSpentIndexValue, CSpentIndexKeyCompare>::iterator it = mapSpent.find(key);
Definitely need to use auto for such long iterator expressions

2021-06-01 15:58 UTC, akobrin1 requested changes

2021-06-01 15:58 UTC, akobrin1 commented on src/script/script.h
> +    // insightexplorer, there may be more script types in the future
use enum class ScriptType, and change in the code ScriptType::P2PKH, etc...

2021-06-01 15:58 UTC, akobrin1 commented on src/script/script.cpp
> +uint160 CScript::AddressHash() const
looks like a candidate for "noexcept"

2021-06-01 15:58 UTC, akobrin1 commented on src/spentindex.h
> +    CSpentIndexValue(uint256 t, unsigned int i, int h, CAmount s, int type, uint160 a) {
mark all parameters const

2021-06-01 15:58 UTC, akobrin1 commented on src/spentindex.h
> +    bool IsNull() const {
noexcept

2021-06-01 19:25 UTC, tsimafeisetchinava000 commented on src/rpc/blockchain.cpp
> +                inputs.push_back(delta);
`inputs.push_back(delta) => inputs.push_back(std::move(delta));`

2021-06-01 20:17 UTC, tsimafeisetchinava000 commented on src/script/script.cpp
> +    vector<unsigned char> hashBytes(this->begin()+start, this->begin()+start+20);
src/prevector.h : line 278
```
iterator begin() { return iterator(item_ptr(0)); }
const_iterator begin() const { return const_iterator(item_ptr(0)); }
```

so I didn't replace begin() to cbegin()

2021-06-02 15:10 UTC, akobrin1 commented
Please rebase on current master branch. Note that serialization template methods were changed. 
Resolve conflicts in script.h & main.h.

2021-06-09 20:06 UTC, a-ok123 approved these changes

2021-06-21 01:18 UTC, closed without merging