Updated Art Reg ticket Json structure & code review
pastelnetwork/pastel pull request #39
Opened 2021-06-21 09:34 UTC by VitaliyVK777

2021-06-22 03:51 UTC, akobrin1 requested changes

2021-06-22 03:51 UTC, akobrin1 commented on src/mnode/mnode-rpc.cpp
> +          mnObj.pushKV(RPC_KEY_TXID, txid);
move(txid)

2021-06-22 05:31 UTC, VitaliyVK777 commented on src/mnode/mnode-rpc.cpp
> +          mnObj.pushKV(RPC_KEY_TXID, txid);
ok

2021-07-17 20:28 UTC, akobrin1 submitted a review, later dismissed
Looks good

2021-07-18 05:22 UTC, VitaliyVK777 commented on qa/rpc-tests/mn_tickets.py
> +        self.nonmn7_green_pastelid1 = self.nodes[self.non_mn7].pastelid("newkey", "passphrase")["pastelid"]
ok. good

2021-07-18 13:26 UTC, a-ok123 approved these changes

2021-07-18 16:58 UTC, vadymeng0 approved these changes

2021-07-19 13:46 UTC, a-ok123 approved these changes

2021-07-19 14:21 UTC, merged