I returned change to the sender wallet
pastelnetwork/pastel pull request #45
Opened 2021-06-26 13:09 UTC by ak-toktor

2021-06-29 15:38 UTC, vadymeng0 commented
Could you please provide below things in the description?
    - What is this task about, and related Freedcamp task.
    - Test result.
    - (If possible) some short description on how you implement it.
 Thank you!!!

2021-06-30 11:17 UTC, vadymeng0 commented on src/wallet/rpcwallet.cpp
> +UniValue z_sendmanyimpl(const UniValue& params, bool fHelp, const std::string& functionName, bool returnChangeToSenderAddr)
These two parameter has the same meaning. Should we deduct one?

2021-06-30 11:19 UTC, vadymeng0 commented on src/wallet/rpcwallet.cpp
> +            CAmount nBalance = getBalanceTaddr(fromaddress, nMinDepth, false);
In the case we return change to sender address, a new operation will still be added to the global queue? Is that mean another transaction will be created?

2021-06-30 11:20 UTC, vadymeng0 commented on src/wallet/rpcwallet.cpp
> +    { "wallet",             "z_sendmanywithchangetosender", &z_sendmanywithchangetosender, false },
This is **NOT** following the latest requirement that is suggested by @a-ok123 and @Dicklesworthstone 
We need to add _additional flag_ to `z_sendmany`, so the implementation must support:
    - `z_sendmany` (without additional flag): just behave old implementation. 
    - `z_sendmany -changetosendingaddress`: do the change utxo change back to the old address.
But you are creating a brand new command `z_sendmanywithchangetosender`.

2021-07-08 03:01 UTC, vadymeng0 commented
This is reimplemented in: https://github.com/pastelnetwork/pastel/pull/51

2021-07-08 03:04 UTC, vadymeng0 commented
I close this PR be cause it basically do not solve the problem.

2021-07-13 05:57 UTC, vadymeng0 requested changes
Basically this change is adding more transaction to send the change back to the sender, but it **_do NOT remove the part that new address is generated and the change is sending to that new address_**.

2021-07-15 18:44 UTC, closed without merging

2021-07-15 18:44 UTC, a-ok123 commented
replaced by PR51