Initial draft version of Gift, GiftAccept & Give tickets
pastelnetwork/pastel pull request #46
Opened 2021-06-29 07:53 UTC by VitaliyVK777

2021-07-12 11:14 UTC, vadymeng0 commented on src/mnode/mnode-pastel.cpp
> +std::string CArtSellTicket::ToStr() const noexcept {
Lots of the changes is about code-formatting differences only.
This makes the changes hard to review.
Does the coding convention changed intentionally?

2021-07-13 04:23 UTC, a-ok123 requested changes
There are too many changes - this SHALL NOT be merged until further notice

2021-07-13 18:45 UTC, VitaliyVK777 commented on src/mnode/mnode-pastel.cpp
> +bool trade_copy_validation(const std::string& nftTnxId, const std::vector<unsigned char>& signature) {
ok

2021-07-13 18:45 UTC, VitaliyVK777 commented on src/mnode/mnode-pastel.cpp
> +  if (masterNodeCtrl.masternodeSync.IsSynced()) {
ok

2023-10-04 00:47 UTC, closed without merging