PSL-119 - better error message
pastelnetwork/pastel pull request #88
Opened 2021-12-15 13:12 UTC by tanlemin91

- need better error message about wrong  password

2021-12-15 20:42 UTC, akobrin2 requested changes
There are multiple reasons why secure container cannot be read:
1) no access to file or file does not exist
2) file is locked for read
3) invalid file format - any validation fails
The only case when it fails because of incorrect passphrase is when crypto_aead_xchacha20poly1305_ietf_decrypt function fails and returns "Failed to decrypt secure item data' message. Just set some bool flag here and handle it in catch (const std::exception &ex). Or, even better, define custom exception from runtime_exception (let's say secure_container_exception with specific code & message), then add one more catch for that new exception.

2021-12-16 12:47 UTC, tanlemin91 commented
> There are multiple reasons why secure container cannot be read:
> 
> 1. no access to file or file does not exist
> 2. file is locked for read
> 3. invalid file format - any validation fails
>    The only case when it fails because of incorrect passphrase is when crypto_aead_xchacha20poly1305_ietf_decrypt function fails and returns "Failed to decrypt secure item data' message. Just set some bool flag here and handle it in catch (const std::exception &ex). Or, even better, define custom exception from runtime_exception (let's say secure_container_exception with specific code & message), then add one more catch for that new exception.

2021-12-16 17:06 UTC, a-ok123 approved these changes

2021-12-16 17:22 UTC, akobrin1 approved these changes
looks good

2021-12-17 16:31 UTC, a-ok123 approved these changes

2021-12-17 16:43 UTC, merged