Psl 165 convert uint256 test arith uint256 test
pastelnetwork/pastel pull request #90
Opened 2021-12-18 13:53 UTC by tanlemin91

- convert uint256_tests.cpp, arith_uint256_tests.cpp to pastel_gtest
- add uint256_tests.cpp, arith_uint256_tests.cpp into pastel_gtest
- remove uint256_tests.cpp, arith_uint256_tests.cpp from test_bitcoin

2021-12-18 14:03 UTC, tanlemin91 reviewed
Please review @a-ok123 @akobrin2

2021-12-18 20:55 UTC, akobrin1 requested changes
please review all EXPECT_xxxx macros

2021-12-18 20:55 UTC, akobrin1 commented on src/gtest/test_arith_uint256.cpp
> +#include "test/test_bitcoin.h"
remove test_bitcoin.h, the goal is to remove all connections to boost

2021-12-18 20:55 UTC, akobrin1 commented on src/gtest/test_arith_uint256.cpp
> +    EXPECT_TRUE(OneL.ToString() != ArrToStr(ZeroArray,32));
replace EXPECT_TRUE(a != b) with EXPECT_NE(a, b)
and all similar cases below

2021-12-18 20:55 UTC, akobrin1 commented on src/gtest/test_arith_uint256.cpp
> +    EXPECT_TRUE(~MaxL == ZeroL);
this one is EXPECT_EQ

2021-12-18 20:55 UTC, akobrin1 commented on src/gtest/test_arith_uint256.cpp
> +        EXPECT_TRUE(ZeroL != (OneL << i));
EXPECT_NE - all 4

2021-12-18 20:55 UTC, akobrin1 commented on src/gtest/test_arith_uint256.cpp
> +    EXPECT_TRUE(ZeroL == (OneL << 256));
EXPECT_EQ all below

2021-12-18 20:55 UTC, akobrin1 commented on src/gtest/test_arith_uint256.cpp
> +        EXPECT_TRUE(arith_uint256V(std::vector<unsigned char>(TmpArray,TmpArray+32)) == (OneL << i));
add #include <vector_types.h> and replace all vector<unsigned char> with v_uint8.
all std:: can be removed in this file - you have "using namespace std" defined

2021-12-18 20:55 UTC, akobrin1 commented on src/gtest/test_arith_uint256.cpp
> +    EXPECT_TRUE(~ZeroL == MaxL);
EXPECT_TRUE=> EXPECT_EQ

2021-12-18 20:55 UTC, akobrin1 commented on src/gtest/test_arith_uint256.cpp
> +    TmpL = _A_##L; TmpL _OP_##= _B_##L; EXPECT_TRUE(TmpL == (_A_##L _OP_ _B_##L));
this EXPECT_TRUE in macro also to EXPECT_EQ

2021-12-18 20:55 UTC, akobrin1 commented on src/gtest/test_arith_uint256.cpp
> +    EXPECT_EQ(fNegative, false);
EXPECT_EQ => EXPECT_FALSE,
all fNegative, fOverflow checks below... some of them EXPECT_TRUE, some EXPECT_FALSE

2021-12-18 20:55 UTC, akobrin1 commented on src/gtest/test_arith_uint256.cpp
> +#include <gtest/gtest.h>
you can delete gtest.h here, gmock.h includes gtest.h

2021-12-18 20:55 UTC, akobrin1 commented on src/gtest/test_uint256.cpp
> +#include "test/test_bitcoin.h"
remove test_bitcoin.h & gtest.h

2021-12-19 21:20 UTC, akobrin1 approved these changes
You could convert some tests to parameterized.
Especially tests with lots of repetitions, like bignum_SetCompact.
See for example test_bech32.cpp. In this test, you could use tuple<uint32_t, string, uint32_t, bool, bool> - simply all parameters used in the test. Then just write the actual test once and define all parameters via INSTANTIATE_TEST_SUITE_P && Values(make_tuple(...), )

2021-12-19 22:06 UTC, a-ok123 approved these changes

2021-12-21 16:17 UTC, merged