Psl 197 convert pastel gtest
pastelnetwork/pastel pull request #98
Opened 2021-12-31 16:32 UTC by tanlemin91

2022-01-06 07:30 UTC, akobrin1 requested changes

2022-01-06 07:30 UTC, akobrin1 commented on src/gtest/test_dbwrapper.cpp
> +    boost::scoped_ptr<CDBIterator> it(const_cast<CDBWrapper*>(&dbw)->NewIterator());
please replace boost::scoped_ptr with std::unique_ptr

2022-01-06 07:30 UTC, akobrin1 commented on src/gtest/test_dbwrapper.cpp
> +    boost::scoped_ptr<CDBIterator> it(const_cast<CDBWrapper*>(&dbw)->NewIterator());
same

2022-01-06 12:26 UTC, tanlemin91 commented on src/gtest/test_dbwrapper.cpp
> +    boost::scoped_ptr<CDBIterator> it(const_cast<CDBWrapper*>(&dbw)->NewIterator());
thanks, fixed,

2022-01-06 12:26 UTC, tanlemin91 commented on src/gtest/test_dbwrapper.cpp
> +    boost::scoped_ptr<CDBIterator> it(const_cast<CDBWrapper*>(&dbw)->NewIterator());
thanks, fixed,

2022-01-10 14:49 UTC, akobrin1 approved these changes

2022-01-10 14:49 UTC, merged